#
#===================================================
# Xiaolu Zhang 886161
# Jianbo Ma 807590
# Hongyi Lin 838776
# Xiaoyu Wang 799778
# Shalitha Weerakoon Karunatilleke 822379

# COMP90024 Cluster and Cloud Computing
# Social Media Analytics on Melbourne & Sydney
#====================================================
#

---
#- name: install pip packages
#  pip: name={{ item }} executable=pip3
#  with_items:
#    - tweepy
#    - pycouchdb
#    - nltk
#    - textblob
#    - python-dateutil
#    - shapely
#    - mpi4py
#  tags: processor
#
#- name: ntlk modules
#  shell: python3 -m nltk.downloader stopwords

- name: make directories
  file: path={{ item }} state=directory mode=0755 owner=ubuntu group=ubuntu
  with_items:
    - "{{ project_scripts }}"
  tags: processor

- name: downlaod scripts and files from github
  git: repo=https://github.com/apache/couchdb.git dest={{ project_scripts }} accept_hostkey=yes
  tags: processor
