#
#===================================================
# Xiaolu Zhang 886161
# Jianbo Ma 807590
# Hongyi Lin 838776
# Xiaoyu Wang 799778
# Shalitha Weerakoon Karunatilleke 822379

# COMP90024 Cluster and Cloud Computing
# Social Media Analytics on Melbourne & Sydney
#====================================================
#

admin_user: admin
admin_pass: admin*230

project_scripts: /home/ubuntu/ccc
tomcat_version: 'apache-tomcat-8.5.9'
tomcat_home: '/opt/{{tomcat_version}}'
