#
#===================================================
# Xiaolu Zhang 886161
# Jianbo Ma 807590
# Hongyi Lin 838776
# Xiaoyu Wang 799778
# Shalitha Weerakoon Karunatilleke 822379

# COMP90024 Cluster and Cloud Computing
# Social Media Analytics on Melbourne & Sydney
#====================================================
#

#---
#- name: check connection to CouchDB instances
#  uri:
#    url: http://{{ inventory_hostname }}:{{ item }}/
#    method: GET
#    status_code: 200
#  with_items: '{{couchdb_ports}}'
#  tags: config
#
##- name: create admin user
##  uri:
##    url: http://127.0.0.1:{{ couchdb_chttpd_port }}/_node/ubuntu@{{ item }}/_config/admins
##    body: "{}"
##    user: "{{ admin_user | default(omit) }}"
##    password: "{{ admin_pass | default(omit) }}"
##    force_basic_auth: "{{ admin_user | length > 0 }}"
##    status_code: 200,201,412
##    body_format: json
##    with_items: "{{ groups['servers'] }}"
##  tags: config
#
#- name: create admin user
#  command: curl -X PUT http://127.0.0.1:{{ couchdb_chttpd_port }}/_node/ubuntu@{{ inventory_hostname }}/_config/admins/{{ admin_user }} -d '"{{ admin_pass }}"'
#  tags: cluster
#
#- name: add nodes to cluster
#  uri:
#    url: http://127.0.0.1:{{ couchdb_httpd_port }}/_nodes/ubuntu@{{ item }}
#    method: PUT
#    body: "{}"
#    user: "{{ admin_user | default(omit) }}"
#    password: "{{ admin_pass | default(omit) }}"
#    force_basic_auth: "{{ admin_user | length > 0 }}"
#    status_code: 200,201,412
#    body_format: json
#  with_items: "{{ groups['servers'] }}"
#  when: inventory_hostname == groups['servers'][0] and inventory_hostname != item
#  tags: config
#
#- name: create databases
#  uri:
#    url: http://127.0.0.1:{{ couchdb_chttpd_port }}/{{ item.key }}
#    method: PUT
#    user: "{{ admin_user | default(omit) }}"
#    password: "{{ admin_pass | default(omit) }}"
#    force_basic_auth: "{{ admin_user | length > 0 }}"
#    status_code: 201,412
#  with_dict: "{{ couchdb_databases }}"
#  when: inventory_hostname == groups['servers'][0]
#  tags: config
#
#- name: secure databases
#  uri:
#    url: http://127.0.0.1:{{ couchdb_chttpd_port }}/{{ item.key }}/_security
#    method: PUT
#    user: "{{ admin_user | default(omit) }}"
#    password: "{{ admin_pass | default(omit) }}"
#    force_basic_auth: "{{ admin_user | length > 0 }}"
#    body_format: json
#    body:
#      admins: "{{ item.value.admins | default({}) }}"
#      members: "{{ item.value.members | default({}) }}"
#    status_code: 200
#  with_dict: "{{ couchdb_databases }}"
#  when: inventory_hostname == groups['servers'][0] and ('admins' in item.value or 'members' in item.value)
#  tags: config
